### ISSUE TITLE
Bug report [Forge / Fabric]

### ISSUE THREAD

**Issue by texxzera** [samolego/Taterzens#104]
**Describe the bug**
I add a taterzen but when I go to remove it I get disconnected from the server.
![download](https://user-images.githubusercontent.com/107436543/174102221-392a63c6-60dd-494c-9000-fa46957a4016.png)

**Platform(s)**

- [x] Fabric

- [ ] Forge

**Environment(s)**

- [ ] Singleplayer
- [x] Server

**Versions**
* Minecraft 1.19
* Taterzens 1.10.4

**Comment by samolego** [comment]
Please provide the whole log as well.

**Comment by texxzera** [comment]
[latest.log](https://github.com/samolego/Taterzens/files/8922074/latest.log)

**Comment by samolego** [comment]
So spawning works fine, but you get kicked on /npc remove ?

**Comment by texxzera** [comment]
yes, I recorded a video that better demonstrates the bug
https://www.youtube.com/watch?v=gvAgij5F9Kw
