### ISSUE TITLE
Server doesnt start

### ISSUE THREAD

**Issue by Hyundai0** [samolego/Taterzens#105]
**Describe the bug**

**Platform(s)**

Fabric

**Environment(s)**

 Server

**Versions**
* Minecraft 1.18.1
* Taterzens taterzens-1.10.4-fabric.jar

**To Reproduce**
1. Launch server
2. See error

**Expected behavior**

**Logs**

<details>
  <summary>Logs</summary>
Please paste your <a href="https://fabricmc.net/wiki/player:tutorials:logs_ml:windows">
D:\dad23123>java -Xmx4G -jar fabric-server-launch.jar nogui
Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
[17:40:40] [INFO] [FabricLoader/GameProvider]: Loading Minecraft 1.18.1 with Fabric Loader 0.12.12
[17:40:40] [main/INFO]: Loading Minecraft 1.18.1 with Fabric Loader 0.12.12
[17:40:40] [main/WARN]: Mod resolution failed
[17:40:40] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE taterzens 1.10.4 {depends fabric @ [>=0.48.0]}, ROOT_FORCELOAD_SINGLE taterzens 1.10.4]
[17:40:40] [main/INFO]: Reason: [HARD_DEP taterzens 1.10.4 {depends fabric @ [>=0.48.0]}, HARD_DEP server_translations_api 1.4.14+1.19-rc2 {depends minecraft @ [>=1.19-alpha.22.16.a]}, HARD_DEP sgui 1.1.0+1.19 {depends minecraft @ [>=1.18.2]}]
[17:40:40] [main/INFO]: SERVER environment disabled: [fabric-renderer-api-v1, fabric-keybindings-v0, fabric-textures-v0, tweakeroo, malilib, fabric-screen-api-v1, fabric-renderer-indigo, litematica, autoclicker-fabric, fabric-blockrenderlayer-v1, fabric-renderer-registries-v1, minihud, fabric-models-v0, fabric-rendering-v0, fabric-key-binding-api-v1, fabric-rendering-v1]
[17:40:40] [main/INFO]: Fix: add [], remove [], replace [[taterzens 1.10.4] -> add:taterzens 1 ([(-∞,∞)])]
[17:40:40] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
         - Replace mod 'Taterzens' (taterzens) 1.10.4 (D:\dad23123\mods\taterzens-1.10.4-fabric.jar) with any version that is compatible with:
                 - fabric 0.45.2+1.18
Unmet dependency listing:
         - Mod 'Taterzens' (taterzens) 1.10.4 requires version 0.48.0 or later of mod 'Fabric API' (fabric), but only the wrong version is present: 0.45.2+1.18!
                 - Mod 'Fabric API' (fabric) 0.45.2+1.18 is being loaded from D:\dad23123\mods\fabric-api-0.45.2+1.18.jar
         - Mod 'Server Translations API' (server_translations_api) 1.4.14+1.19-rc2 requires version 1.19-alpha.22.16.a or later of 'Minecraft' (minecraft), but only the wrong version is present: 1.18.1!
                 - 'Minecraft' (minecraft) 1.18.1 is an environment reference and usually requires installation or launcher changes to adjust
         - Mod 'sgui' (sgui) 1.1.0+1.19 requires version 1.18.2 or later of 'Minecraft' (minecraft), but only the wrong version is present: 1.18.1!
                 - 'Minecraft' (minecraft) 1.18.1 is an environment reference and usually requires installation or launcher changes to adjust
Inactive mods:
         - mod 'Auto Clicker' (autoclicker-fabric) 1.18-1.3.0-build.16, reason: wrong environment (client/server only)
         - mod 'Litematica' (litematica) 0.10.4, reason: wrong environment (client/server only)
         - mod 'MaLiLib' (malilib) 0.11.8, reason: wrong environment (client/server only)
         - mod 'MiniHUD' (minihud) 0.21.5, reason: wrong environment (client/server only)
         - mod 'Taterzens' (taterzens) 1.10.4, reason: to replace
         - mod 'Tweakeroo' (tweakeroo) 0.12.3, reason: wrong environment (client/server only)
         - mod 'Tweakeroo' (tweakeroo) 1.2.3, reason: wrong environment (client/server only)
         - mod 'Config to Brigadier' (config2brigadier) 1.1.4, reason: inactive parent mod (nested jar)
         - mod 'Fabric API Base' (fabric-api-base) 0.4.1+b4f4f6cdc8, reason: newer version active
         - mod 'Fabric BlockRenderLayer Registration (v1)' (fabric-blockrenderlayer-v1) 1.1.9+3ac43d9565, reason: wrong environment (client/server only)
         - mod 'Fabric Command API (v1)' (fabric-command-api-v1) 1.1.6+3ac43d95c8, reason: newer version active
         - mod 'Fabric Events Interaction (v0)' (fabric-events-interaction-v0) 0.4.16+bfa23f17c8, reason: newer version active
         - mod 'Fabric Key Binding API (v1)' (fabric-key-binding-api-v1) 1.0.8+c8aba2f365, reason: wrong environment (client/server only)
         - mod 'Fabric Key Bindings (v0)' (fabric-keybindings-v0) 0.2.6+b4f4f6cd65, reason: wrong environment (client/server only)
         - mod 'Fabric Lifecycle Events (v1)' (fabric-lifecycle-events-v1) 1.4.10+c15ca335c8, reason: newer version active
         - mod 'Fabric Models (v0)' (fabric-models-v0) 0.3.3+3ac43d9565, reason: wrong environment (client/server only)
         - mod 'Fabric Networking API (v1)' (fabric-networking-api-v1) 1.0.18+3ac43d95c8, reason: newer version active
         - mod 'fabric-permissions-api' (fabric-permissions-api-v0) 0.1-SNAPSHOT, reason: inactive parent mod (nested jar)
         - mod 'Fabric Renderer API (v1)' (fabric-renderer-api-v1) 0.4.9+3ac43d9565, reason: wrong environment (client/server only)
         - mod 'Fabric Renderer - Indigo' (fabric-renderer-indigo) 0.4.12+3ac43d9565, reason: wrong environment (client/server only)
         - mod 'Fabric Renderer Registries (v1)' (fabric-renderer-registries-v1) 3.2.7+b4f4f6cd65, reason: wrong environment (client/server only)
         - mod 'Fabric Rendering (v0)' (fabric-rendering-v0) 1.1.9+b4f4f6cd65, reason: wrong environment (client/server only)
         - mod 'Fabric Rendering (v1)' (fabric-rendering-v1) 1.10.3+6b21378a65, reason: wrong environment (client/server only)
         - mod 'Fabric Screen API (v1)' (fabric-screen-api-v1) 1.0.7+3ac43d9565, reason: wrong environment (client/server only)
         - mod 'Fabric Textures (v0)' (fabric-textures-v0) 1.0.9+3ac43d9565, reason: wrong environment (client/server only)
         - mod 'Packet Tweaker' (packet_tweaker) 0.3.0+1.18.2, reason: inactive parent mod (nested jar)
         - mod 'Server Translations API' (server_translations_api) 1.4.14+1.19-rc2, reason: inactive parent mod (nested jar)
         - mod 'sgui' (sgui) 1.1.0+1.19, reason: inactive parent mod (nested jar)
        at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:189) ~[fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142) ~[fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71) [fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.12.12.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) [fabric-loader-0.12.12.jar:?]
Caused by: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
         - Replace mod 'Taterzens' (taterzens) 1.10.4 (D:\dad23123\mods\taterzens-1.10.4-fabric.jar) with any version that is compatible with:
                 - fabric 0.45.2+1.18
Unmet dependency listing:
         - Mod 'Taterzens' (taterzens) 1.10.4 requires version 0.48.0 or later of mod 'Fabric API' (fabric), but only the wrong version is present: 0.45.2+1.18!
                 - Mod 'Fabric API' (fabric) 0.45.2+1.18 is being loaded from D:\dad23123\mods\fabric-api-0.45.2+1.18.jar
         - Mod 'Server Translations API' (server_translations_api) 1.4.14+1.19-rc2 requires version 1.19-alpha.22.16.a or later of 'Minecraft' (minecraft), but only the wrong version is present: 1.18.1!
                 - 'Minecraft' (minecraft) 1.18.1 is an environment reference and usually requires installation or launcher changes to adjust
         - Mod 'sgui' (sgui) 1.1.0+1.19 requires version 1.18.2 or later of 'Minecraft' (minecraft), but only the wrong version is present: 1.18.1!
                 - 'Minecraft' (minecraft) 1.18.1 is an environment reference and usually requires installation or launcher changes to adjust
Inactive mods:
         - mod 'Auto Clicker' (autoclicker-fabric) 1.18-1.3.0-build.16, reason: wrong environment (client/server only)
         - mod 'Litematica' (litematica) 0.10.4, reason: wrong environment (client/server only)
         - mod 'MaLiLib' (malilib) 0.11.8, reason: wrong environment (client/server only)
         - mod 'MiniHUD' (minihud) 0.21.5, reason: wrong environment (client/server only)
         - mod 'Taterzens' (taterzens) 1.10.4, reason: to replace
         - mod 'Tweakeroo' (tweakeroo) 0.12.3, reason: wrong environment (client/server only)
         - mod 'Tweakeroo' (tweakeroo) 1.2.3, reason: wrong environment (client/server only)
         - mod 'Config to Brigadier' (config2brigadier) 1.1.4, reason: inactive parent mod (nested jar)
         - mod 'Fabric API Base' (fabric-api-base) 0.4.1+b4f4f6cdc8, reason: newer version active
         - mod 'Fabric BlockRenderLayer Registration (v1)' (fabric-blockrenderlayer-v1) 1.1.9+3ac43d9565, reason: wrong environment (client/server only)
         - mod 'Fabric Command API (v1)' (fabric-command-api-v1) 1.1.6+3ac43d95c8, reason: newer version active
         - mod 'Fabric Events Interaction (v0)' (fabric-events-interaction-v0) 0.4.16+bfa23f17c8, reason: newer version active
         - mod 'Fabric Key Binding API (v1)' (fabric-key-binding-api-v1) 1.0.8+c8aba2f365, reason: wrong environment (client/server only)
         - mod 'Fabric Key Bindings (v0)' (fabric-keybindings-v0) 0.2.6+b4f4f6cd65, reason: wrong environment (client/server only)
         - mod 'Fabric Lifecycle Events (v1)' (fabric-lifecycle-events-v1) 1.4.10+c15ca335c8, reason: newer version active
         - mod 'Fabric Models (v0)' (fabric-models-v0) 0.3.3+3ac43d9565, reason: wrong environment (client/server only)
         - mod 'Fabric Networking API (v1)' (fabric-networking-api-v1) 1.0.18+3ac43d95c8, reason: newer version active
         - mod 'fabric-permissions-api' (fabric-permissions-api-v0) 0.1-SNAPSHOT, reason: inactive parent mod (nested jar)
         - mod 'Fabric Renderer API (v1)' (fabric-renderer-api-v1) 0.4.9+3ac43d9565, reason: wrong environment (client/server only)
         - mod 'Fabric Renderer - Indigo' (fabric-renderer-indigo) 0.4.12+3ac43d9565, reason: wrong environment (client/server only)
         - mod 'Fabric Renderer Registries (v1)' (fabric-renderer-registries-v1) 3.2.7+b4f4f6cd65, reason: wrong environment (client/server only)
         - mod 'Fabric Rendering (v0)' (fabric-rendering-v0) 1.1.9+b4f4f6cd65, reason: wrong environment (client/server only)
         - mod 'Fabric Rendering (v1)' (fabric-rendering-v1) 1.10.3+6b21378a65, reason: wrong environment (client/server only)
         - mod 'Fabric Screen API (v1)' (fabric-screen-api-v1) 1.0.7+3ac43d9565, reason: wrong environment (client/server only)
         - mod 'Fabric Textures (v0)' (fabric-textures-v0) 1.0.9+3ac43d9565, reason: wrong environment (client/server only)
         - mod 'Packet Tweaker' (packet_tweaker) 0.3.0+1.18.2, reason: inactive parent mod (nested jar)
         - mod 'Server Translations API' (server_translations_api) 1.4.14+1.19-rc2, reason: inactive parent mod (nested jar)
         - mod 'sgui' (sgui) 1.1.0+1.19, reason: inactive parent mod (nested jar)
        at net.fabricmc.loader.impl.discovery.ModResolver.findCompatibleSet(ModResolver.java:159) ~[fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:45) ~[fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:224) ~[fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:187) ~[fabric-loader-0.12.12.jar:?]
        ... 8 more</a> here or include a link to a third party site.
</details>

**Additional context**

**Comment by samolego** [comment]
Update fabric
