### ISSUE TITLE
Bug report [Forge / Fabric]

### ISSUE THREAD

**Issue by NinesChaosu** [samolego/Taterzens#106]
**Describe the bug**
Equipment option in gui doesn't work after pressing it shows "incorrect argument for command"

**Platform(s)**

- [x] Fabric
- [] Forge

**Environment(s)**

- [x] Singleplayer
- [] Server

**Versions**
* Minecraft 1.19
* Taterzens 1.10.4

**To Reproduce**
1.Create NPC
2. Right Click on NPC
3. Right Click on Edit then Equipment
4. Right Clicking on Done

**Expected behavior**

**Logs**

<details>
  <summary>Logs</summary>
Please paste your <a href="https://fabricmc.net/wiki/player:tutorials:logs_ml:windows">log</a> here or include a link to a third party site.
</details>

**Additional context**

**Comment by samolego** [comment]
You must right-click the chestplate icon to launch the editor. I might swap that though
