### ISSUE TITLE
Bug report [ Fabric] Opening the GUI of survival trader crashes the server

### ISSUE THREAD

**Issue by TheRobberPanda** [samolego/Taterzens#108]
**Describe the bug**
As in the title Opening the GUI of survival trader crashes the server

**Platform(s)**

- [x] Fabric

**Environment(s)**

- [x] Server

**Versions**
* Minecraft 1.18.2
* Taterzens 1.9.6

**To Reproduce**
1 - Giving an NPC the profession of survival trader 
2 - Right clicking on said NPC
3 - Clicking on "edit"

**Expected behavior**
GUI to edit trades should open

**Logs**

[crash-2022-07-08_20.37.02-server.txt](https://github.com/samolego/Taterzens/files/9074452/crash-2022-07-08_20.37.02-server.txt)

**Additional context**
Active user, please conctact me if necessary.

**Comment by samolego** [comment]
same as #110
