### ISSUE TITLE
Config file bug report [Fabric]

### ISSUE THREAD

**Issue by TheRobberPanda** [samolego/Taterzens#109]
**Describe the bug**
When editing the delay for messages they wont actually change

**Platform(s)**

- [x] Fabric

**Environment(s)**

- [x] Server

**Versions**
* Minecraft 1.18.2
* Taterzens 1.9.6

**To Reproduce**
1. Change message_delay in config file for taterzens to anything above delfault
2. Run server
3. Program taterzen so it speaks any random message
4. The Taterzen will still speak with the default delay and repeat the message each

**Expected behavior**

**Logs**

No log since the action doesn't register in it.

</details>

**Additional context**
Contact if needed, I'll always be available to help a mod developer

**Comment by samolego** [comment]
Ough, this must be an oversight then. Thanks for reporting!

**Comment by samolego** [comment]
Have you added new messages after changing delay?

**Comment by TheRobberPanda** [comment]
I did add new messages. It did work but I had to restart the server twice. I now realize it could've been an error on my end. In case you dont find anything wrong.
