### ISSUE TITLE
The game randomly crashes when the npc is following a path

### ISSUE THREAD

**Issue by Enessounnet** [samolego/Taterzens#11]
Here's the crash report :

[crash-2021-04-25_21.17.56-server.txt](https://github.com/samolego/Taterzens/files/6372797/crash-2021-04-25_21.17.56-server.txt)

**Comment by samolego** [comment]
Thanks for report! Were you changing the path when it happened?

**Comment by Enessounnet** [comment]
No, the NPC was just following the path
