### ISSUE TITLE
GUI crashes game [Fabric]

### ISSUE THREAD

**Issue by TheRobberPanda** [samolego/Taterzens#110]
**Describe the bug**
After opening the GUI for presets>Load>then writing the name of a preexisting Preset the game will crash

**Platform(s)**

- [x] Fabric

**Environment(s)**

- [x] Server

**Versions**
* Minecraft 1.18.2
* Taterzens 1.9.6

**To Reproduce**
1. Launch server '...'
2. create taterzen and save it as a preset 
3. Delete said taterzen
4. Open the GUI of a new taterzen by right-clicking on it and then open the "presets" menu.
5. Click load
6. Type the name with which you had saved the first taterzen
7. The game will now crash

**Expected behavior**
The GUI opens normally

**Logs**

[crash-2022-07-09_14.28.47-client.txt](https://github.com/samolego/Taterzens/files/9076514/crash-2022-07-09_14.28.47-client.txt)

**Additional context**
Any help needed with it will be provided, if needed contact me

**Comment by samolego** [comment]
You'd need to update to 1.19 or downgrade taterzens
