### ISSUE TITLE
How to change skin with Fabrictailor?

### ISSUE THREAD

**Issue by mocksonline** [samolego/Taterzens#115]
How to change skin with Fabrictailor? 
I setup myself skin a local skin (png image), but when I run `/npc edit skin` (already selected), npc just turned a bit and skin didn't change. 

The mod runs on an offline server, my default skin is Alex, also npc.

**Comment by mocksonline** [comment]
With errcode 
[Server] [05:57:53] [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2824@2f1cae81, suppressing error
[Server] java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
[Server]        at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
[Server]        at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
[Server]        at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
[Server]        at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
[Server]        at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
[Server]        at org.samo_lego.taterzens.npc.commands.CommandGroups.execute(CommandGroups.java:38) ~[taterzens-1.10.4-fabric.jar:?]
[Server]        at org.samo_lego.taterzens.npc.TaterzenNPC.method_5992(TaterzenNPC.java:1134) ~[taterzens-1.10.4-fabric.jar:?]
[Server]        at net.minecraft.class_1308.method_5688(class_1308.java:1135) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_1657.method_7287(class_1657.java:1096) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_3244$1.method_33897(class_3244.java:1511) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_3244$1.method_34219(class_3244.java:1522) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_2824$class_5909.method_34213(class_2824.java:116) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_2824.method_34209(class_2824.java:66) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_3244.method_12062(class_3244.java:1508) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_2824.method_12251(class_2824.java:53) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_2824.method_11054(class_2824.java:13) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:160) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_1255.method_18857(class_1255.java:140) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:737) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.handler$zdl000$modifiedRunLoop(MinecraftServer.java:3889) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:258) ~[server-intermediary.jar:?]
[Server]        at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by samolego** [comment]
Changes to your skin will be reflected to taterzen's one
