### ISSUE TITLE
Lithium incompatibility on entity collisions

### ISSUE THREAD

**Issue by BoredBrownBear** [samolego/Taterzens#12]
**Issue**
Taterzens aren't able to detect nearby player entities, so they don't look or send messages to the player. They can still detect hostile mobs. 

**Steps to reproduce**
Install Lithium

**Workaround**
Set _lithium.properties_ to `mixin.entity.collisions=false`

With that, I'm assuming the issue lies here in [TaterzenNPC.java](https://github.com/samolego/Taterzens/blob/6c4401730dcfc843dad2bd5b4029d299ebb5a47a/common/src/main/java/org/samo_lego/taterzens/npc/TaterzenNPC.java#L349), where the code is incompatible with Lithium's optimization.

**Comment by samolego** [comment]
Thanks for reporting!

**Comment by samolego** [comment]
This is still the case for messages. I'll report it in Lithium.
