### ISSUE TITLE
Bug report [Forge]

### ISSUE THREAD

**Issue by JadeOfTheSky** [samolego/Taterzens#122]
**Describe the bug**
Taterzen's NPCs does not load using the most recent version of forge along with the most recent version of the mod.

**Platform(s)**

- [x] Forge

**Environment(s)**

- [x] Singleplayer

**Versions**
* Minecraft Forge 1.19.2 43.1.57
* Taterzen's Forge 1.10.5

**To Reproduce**

1. Load only Taterzen's in the mods folder
2. Open the game
3. Get error, game will not load.

**Expected behavior**
The mod should load as intended.

**Logs**

<details>
  <summary>Logs</summary>
(https://pastebin.com/yH9ZE7Tq)
</details>

**Comment by samolego** [comment]
1.19.2 is not supported.
