### ISSUE TITLE
Taterzens doesn't work as server-side-only mod on Quilt

### ISSUE THREAD

**Issue by slava110** [samolego/Taterzens#124]
**Describe the bug**
Quilt server with Taterzens mod installed won't allow connecting to it unless it presents on client side too.

**Platform(s)**

- [ ] Fabric
- [ ] Forge
- [x] Quilt

**Environment(s)**

- [ ] Singleplayer
- [x] Server

**Versions**
* Minecraft **1.19.2**
* Quilt Loader **0.17.7** and **0.18.1-beta.21**
* Taterzens **1.11.1**

**To Reproduce**
1. Launch the server
2. Try to connect using vanilla client / client without taterzens mod
3. If you're using vanilla client, server will just cancel connection, if you're using modded client without taterzens mod, you will get something like that in your logs
![image](https://user-images.githubusercontent.com/26705162/205585629-aae08a8b-3dfa-463f-8383-b00e00425cc3.png)

**Expected behavior**
Ability to connect to the server without installing Taterzens mod on client side

**Logs**
*I'm a bad guy and I attached log as a screenshot, muahahah... Ahem. Yea*

**Additional context**
Discord report: https://discord.com/channels/797713290545332235/808022483868450816/1049150876759113790
( In case of discussions on Discord side )

**Comment by samolego** [comment]
Thanks for reporting, seems like sth. has changed in quilt, I must look at some op Patbox's mods.

**Comment by Patbox** [comment]
You might want to use Polymer's Registry Sync Manipulator (sub)library. It should handle both quilt and fabric and is small anyway

**Comment by samolego** [comment]
Ah, the `polymer-reg-sync-manipulator`? Cool!

**Comment by SzczurekYT** [comment]
I can confirm this.
