### ISSUE TITLE
Can't spawn NPCs in Fabric 1.16.5 

### ISSUE THREAD

**Issue by PoisonKittens56** [samolego/Taterzens#125]
I can't spawn an NPC using either commands, it keeps saying "An unexpected error occurred when trying to execute that command" and I have no clue on how to fix it

**Comment by samolego** [comment]
What show up upon hovering over the error?

**Comment by James103** [comment]
Also, what mods are you running on the server?

**Comment by PoisonKittens56** [comment]
sry about the wait. I forgot to say that I decided to not use the mod
