### ISSUE TITLE
[Fabric] 1.19.2 - NPC presets not loading

### ISSUE THREAD

**Issue by EvionFox** [samolego/Taterzens#126]
When I attempt to load a preset that I have saved, the game instead creates a blank Taterzen with none of the saved settings. If I leave the chunk render area, that blank Taterzen will also despawn and disappear from my NPC list.

**Platform(s)**
- [x] Fabric 1.19.2

**Environment(s)**
- [x] Singleplayer

**Versions**
* Minecraft 1.19.2
* Taterzens 1.11.1
* TraderNPCs 1.2.0

**To Reproduce**
1. Create an NPC preset
2. Use the command /npc preset load namehere

**Expected behavior**
Ideally I want at least all the store information I created in the trade NPC to be saved. Skin and looking behavior would be good too.

**Logs**
Log of the issue in Pastebin: https://pastebin.com/WMSLurpE
The preset JSON file: https://drive.google.com/file/d/1tQ87ivW7TQUdndkdvnEEFHCTR3bD9-ZO/view?usp=sharing

**Additional context**
All the NPCs loaded with the preset look like this screenshot: https://drive.google.com/file/d/1pbNNKwe89zOGqsco9xvu1EukEzJjQYmL/view?usp=sharing

**Comment by samolego** [comment]
Uhm, that's kinda strange ... I remember fixing some preset stuff in 1.19.3 update, could you perhaps try it in newer version?

**Comment by EvionFox** [comment]
Unfortunately I don't think it'll work, because TraderNPCs isn't available for 1.19.3 yet, so it would lose all that preset information anyways.

**Comment by EvionFox** [comment]
I did a only-Fabric-and-Taterzen 1.11.2 test in 1.19.3 and can confirm that the preset I created in there does load correctly with skin and looking changes.
