### ISSUE TITLE
Skin second layer Gone [Fabric] 

### ISSUE THREAD

**Issue by Zytinx** [samolego/Taterzens#127]
**Describe the bug**

**Platform(s)**

- [x] Fabric

**Environment(s)**

- [x] Server

**Versions**
* Minecraft 1.19.2
* Taterzens 1.11.1
* 
**To Reproduce**
1. Launch server 
2. Npc don't have skins

**Expected behavior**
Players and Npc are missing skin, only happens when mod is installed

**Additional context**
When i reinstall the mod "galosphere" the skins come back but then taterzen doesnt work because of the dupe id

**Comment by Zytinx** [comment]
![2023-01-08_19 45 02](https://user-images.githubusercontent.com/93175002/211238829-8372d82a-e898-4af0-b016-e990b0384ddc.png)

**Comment by samolego** [comment]
Try to reset their skin layers
