### ISSUE TITLE
equipping bows/crossbows

### ISSUE THREAD

**Issue by Appalachianginger** [samolego/Taterzens#13]
first off I'm so glad to have an NPC mod in 1.16  so thank you for making Taterzens!!

I'm not sure if this is actually an issue or just not a current feature.

when NPCs are given equipment and set to friendly they only seem to hit mobs with whatever is in their hand which is great if they have a sword or an axe but if you want to have something like archers on a castle wall the runup and smack the mobs with their bows.

**Comment by samolego** [comment]
Thanks for suggestion. It shouldn't be too hard to implement.

**Comment by samolego** [comment]
IMplemented in 1.0.4
