### ISSUE TITLE
npc preset with "follow player" when loaded does not follow player anymore

### ISSUE THREAD

**Issue by thecounter89** [samolego/Taterzens#131]
i created multiple different npcs that are supposed to follow the player and have friendly behavior, i made sure that the preset is saved when the npc is following correctly and fighting mobs correctly, however when i load the preset w commands or a command block the npc has all the data correct but the npc does not follow, fight, or move at all. i made sure its not getting stuck on any blocks or anything, just seems to be an issue w the mod or preset saving for those properties

**Comment by samolego** [comment]
That's due to #89
