### ISSUE TITLE
Bug report [Forge / Fabric]

### ISSUE THREAD

**Issue by zinmaxs** [samolego/Taterzens#136]
**Describe the bug**

**Platform(s)**

- [x] Forge

**Environment(s)**

- [x] Singleplayer

**Versions**
* Minecraft 1.19.2
* Taterzens 1.10.5

**To Reproduce**
1. Launch server 'Launch forge single player minecraft'
2. Run 'Error loading mods
1 error has occured during loading'

**Expected behavior**
The mod does not load on ForgeOptifine 1.19.2 (and without optifine)
[crash-2023-03-29_17.27.34-fml.txt](https://github.com/samolego/Taterzens/files/11098279/crash-2023-03-29_17.27.34-fml.txt)

**Logs**

<details>
  <summary>Logs</summary>
 
[crash-2023-03-29_17.27.34-fml.txt](https://github.com/samolego/Taterzens/files/11098276/crash-2023-03-29_17.27.34-fml.txt)
<script src="https://gist.github.com/zinmaxs/41c8abfc93c3abf7a48c54c9b2919f65.js"></script>
</details>

**Additional context**

**Comment by samolego** [comment]
Forge 1.19.2 is not supported

**Comment by zinmaxs** [comment]
> Forge 1.19.2 is not supported
modrinth site has your mod, and there is forge 1.19.2

![image](https://user-images.githubusercontent.com/129268815/228717438-88f671b2-1d9a-4ac6-bf78-c08979501d34.png)

**Comment by samolego** [comment]
Thsi is not .2
