### ISSUE TITLE
Mixin Error Crash when attempting to launch a development test server with the modImplementation included.

### ISSUE THREAD

**Issue by Blobanium** [samolego/Taterzens#139]
**Describe the bug**

**Platform(s)**

- [x] Fabric

**Environment(s)**

- [x] Server
- [x] Development Enviroment

**Versions**
* Minecraft 1.19.4
* Taterzens 1.11.4-beta3

**To Reproduce**
1. Open a Fabric gradle project
2. Put mod in your build.gradle dependencies
3. Run `gradlew runserver` in your command line
4. Fabric wont start due to a mixin error

**Expected behavior**
I expected minecraft to start up normally

**Logs**
[latest.log](https://github.com/samolego/Tater
[debug.log](https://github.com/samolego/Taterzens/files/11142768/debug.log)
zens/files/11142767/latest.log)

**Additional context**
I posted this example project in a new github.

You can find the [build.gradle file here](https://github.com/Blobanium/BumbleBots/blob/master/build.gradle)

**Comment by samolego** [comment]
Ah doesn't seem like it, it cannot launch in production as well. But it works in dev :thinking:

**Comment by Blobanium** [comment]
Could it be that fabric is not properly exposing the official mojang mappings towards runtime perhaps??

Also to note i did run with official mappings and it worked.

**Comment by samolego** [comment]
What's more strange to me is that when developing balcksmiths 1.19.4, which also require taterzens, this didn't happen ...

**Comment by creatorfromhell** [comment]
This same thing is also happening to me. @Blobanium did you find a fix or maybe an alt?
