### ISSUE TITLE
Bug report [Forge / Fabric]

### ISSUE THREAD

**Issue by Levi0621** [samolego/Taterzens#140]
I can't edit the skins, and if I rename the npc, the skin becomes random. That's all. Does anyone know what the problem is?

**Platform(s)**

- [x] Forge

**Environment(s)**

- [x] Singleplayer
- [x] Server
**Versions**
* Minecraft X.Y.Z
* Taterzens A.B.C

**To Reproduce**
1.I created a NPC
2.I tried to edit the name
3. See error

**Expected behavior**

**Logs**

<details>
  <summary>Logs</summary>
Please paste your <a href="https://fabricmc.net/wiki/player:tutorials:logs_ml:windows">log</a> here or include a link to a third party site.
</details>

**Additional context**
![2023-04-05_13 52 50](https://user-images.githubusercontent.com/129956773/230072656-eb65ad37-8638-4eba-9f1e-4beebef166d8.png)

**Comment by samolego** [comment]
Skins are changed via skin part command, not name. Please see the [docs](https://samolego.github.io/Taterzens/).

**Comment by Levi0621** [comment]
it says skin from taterzen fleched from.... (mineskin URL) but is not fleched.

**Comment by Levi0621** [comment]
I did everything the tutorial asked but the skin didn't change, it says skin from taterzen fleched from.... (mineskin URL) but is not fleched.

**Comment by Levi0621** [comment]
> I did everything the tutorial asked but the skin didn't change, it says skin from taterzen fleched from.... (mineskin URL) but is not fleched.

and after i choose a random name for the npc, it changed a random ski and after i cant change skin, like, mirorring, or from 
mineskinURL

**Comment by samolego** [comment]
Which version?

**Comment by Levi0621** [comment]
> Which version?

1.18.2 Forge

**Comment by samolego** [comment]
Oh ...
The only thing I can think of rn is eyporting npc to preset, editing it manually and loading it.
Which launcher are you using?

**Comment by Levi0621** [comment]
> Oh ... The only thing I can think of rn is eyporting npc to preset, editing it manually and loading it. Which launcher are you using?

TLauncher v2.879

**Comment by samolego** [comment]
Try using different launcher / turning skin system off. TLauncher is not suported.

**Comment by Levi0621** [comment]
> Try using different launcher / turning skin system off. TLauncher is not suported.

Ty bro! I turned off the skin system, and it now working! thank you so much!!
