### ISSUE TITLE
Skin Url Bug to long [Fabric]

### ISSUE THREAD

**Issue by KhaozFrost** [samolego/Taterzens#144]
**Describe the bug**
Cant use skins because it kicks you from server saying skin string is to big

**Platform(s)**

- [x] Fabric
- [] Forge

**Environment(s)**

- [] Singleplayer
- [x] Server

**Versions**
    Minecraft 1.19.2
    Taterzens 1.11.1

**To Reproduce**
1. Attempt to set a skin with the MineSkin site
example:
https://minesk.in/aa4164a3920349ecb248aa9863d33fc4

**Expected behavior**
Kicked from server because 25 characters is to long for skin max 16
![image](https://user-images.githubusercontent.com/15788954/236076424-90b50daf-3f23-4153-931a-7771068e02e1.png)

**Comment by samolego** [comment]
It's due to too long command suggestion. This has been fixed in newer versions of Taterzens.

**Comment by KhaozFrost** [comment]
oh.. well can't actually use 1.19.4 version of taterzen due to cobblemon still being 1.19.2 which a vast majority of owners are running fabric for, but appreciate not wanting to backport the issue to help us with your mod.
