### ISSUE TITLE
Config message_delay function not updating [ 1.18.2 Fabric]

### ISSUE THREAD

**Issue by antoniojacksnn** [samolego/Taterzens#146]
Changed config originally from default 100 ticks to 1000 ticks, since then I have tried to change config to multiple different values and all NPCs have been stuck sending messages every 1000 ticks, despite the config in the server folder stating otherwise. Server has been reset, mineraft has been reloaded, and nothing has changed.

**Minecraft Fabric Server 1.18.2**

- [x] Fabric
- [x] Server

messages section of confid below:

"messages": {
    "// Default delay between each message, in ticks.": "",
    "message_delay": 150,
    "// Whether to exit message editor mode after editing a message.": "",
    "exit_editor_after_msg_edit": true,
    "// Message format. First %s is replaced with name, second one with message.": "",
    "structure": "%s -> you: %s",
    "// How far can player be for messages start appearing.": "(default: 3.0f)",
    "speak_distance": 3.0
  },

**Comment by samolego** [comment]
npc saves all the settings upon creation. New npcs will have longer delay, but you'll have to edit others.
