### ISSUE TITLE
3 Problems with 1.0.4

### ISSUE THREAD

**Issue by Aruscha** [samolego/Taterzens#15]
Hello,

I just became aware of your NPC mod .
However, I have a problem how and what do I have to set so that the NPC's like Zombie and Creepers attack but not themselves among themselves ?

And unfortunately my npc at force path just stops at some point, can I lift that?

And I have the problem that I can't load my presents, it just doesn't create npc...

**Comment by samolego** [comment]
I'm closing this as it's partially resolved. Please update to 1.1.0 and open a new issue for each bug (don't merge them into one report please ;) ).
