### ISSUE TITLE
Can't remove NPCs

### ISSUE THREAD

**Issue by missitaxd** [samolego/Taterzens#157]
**Describe the bug**
When trying to remove a NPC it doesn't work, it stays there.

**Platform(s)**

- [x] Fabric

**Environment(s)**

- [x] Singleplayer

**Versions**
* Minecraft 1.20.1
* Taterzens 1.11.6

**To Reproduce**
1. Launch solo world
2. Run
   /npc select id 3
   /npc remove
3. The NPC doesn't dissapear, it gets deselected.

**Expected behavior**
The NPC should have been removed.

**Comment by samolego** [comment]
Thanks for reporting.
Currently as a workaround you can set invulnerability to false, then kill them manually.

**Comment by leonelcba** [comment]
> Thanks for reporting. Currently as a workaround you can set invulnerability to false, then kill them manually.

What command should be used for that?

**Comment by samolego** [comment]
data merge entity

Or set behaviour to hostile, it'll prompt the invulnerability command if you click on message

**Comment by Ariel515** [comment]
Hello i tried to remove the box with data merge entity but it doesn't works please tell me what I have to do?

**Comment by samolego** [comment]
Should be fixed in 1.11.7
