### ISSUE TITLE
NPC custom names don't work with ViaVersion [Fabric]

### ISSUE THREAD

**Issue by SzczurekYT** [samolego/Taterzens#158]
**Describe the bug**
ViaVersion and ViaBackwards are protocol translators, that let players on newer clients (ViaVersion (ViaFabric)) and older clients (ViaBackwards) join the server.
Now when I connect to 1.20.1 server with Taterzens using 1.20.1 everything is fine.
But when I connect with different version (so the protocol is translated by these mods), custom npc names don't work, and every npc is named \-Taterzen\- (the default name from config).

**Platform(s)**

- [x] Fabric
- [ ] Forge - Not tested, Via* doesn't support forge I think.

**Environment(s)**
- [ ] Singleplayer
- [x] Server

**Versions**
* Minecraft 1.20.1 (server), Client - any other then 1.20.1
* Taterzens 1.20-1.11.6
* ViaFabric 0.4.10+40
* ViaBackwards 4.7.0
* Fabric API 0.85.0+1.20.1

**To Reproduce**
1. Launch server with mods specified above.
2. Connect to server with any version that isn't 1.20.1 so the protocol is translated.
3. Create a npc
4. His nametag is  \-Taterzen\- instead of the custom name. 

**Expected behavior**
The name should be correct.

**Logs**
No errors in the log, nothing useful so I'm not pasting them.

**Additional context**
No

**Comment by samolego** [comment]
Thanks for reporting; though I'd say this is more of a viaversion issue ..?

**Comment by SzczurekYT** [comment]
Yeah... Good chance it is. I'm gonna ask them on their discord, and see if they have an idea where is the problem and which side should fix this.
