### ISSUE TITLE
Question: Will there be a Forge 1.19.2 Version? [Forge]

### ISSUE THREAD

**Issue by Aska-Dev** [samolego/Taterzens#159]
**Describe the bug**
Hello, sorry that I might use the Bug Report to establish just communication! I really want to use a NPC mod to make my own custom NPCs in the game for a server rpg, but sadly there is none for the version 1.19.2 that I know of and I found on my researches. I already enjoyed and experienced this mod and was really pleased with the experience. In addition the mod is still in development and already has Fabric Versions for the said Minecraft Version. 

That's why I am asking if there are any plans for upgrading to version 1.19.2 for Forge Loader? (i'm aware of the difficulties with Version Upgrades in Forge and the really more comfortable enviroment of Fabric) 

**Platform(s)**

- [] Fabric
- [x] Forge

**Environment(s)**

- [x] Singleplayer
- [x] Server

**Versions**
* Minecraft 1.19.2
* Taterzens XXX

**Additional context**
Again: Sorry for missusing the Bug Report Tool and thank you already for an answer and your awesome work on that mod!

**Comment by samolego** [comment]
No, sorry.
