### ISSUE TITLE
Merge TraderNPCs into the base mod [Forge / Fabric]

### ISSUE THREAD

**Issue by IoIxD** [samolego/Taterzens#172]
**Describe the bug**
The reason I found out about the last issue I opened was because I wanted to change a NPC's type to villager, but apparently I'm supposed to use just use your "TraderNPCs" addon. This addon also isn't updated and won't work on 1.20.1, but I actually wanted to open a seperate issue to suggest that this functionality just be merged into the base mod, because this is a potentially very common use case for this mod.

**Platform(s)**

- [x] Fabric
- [x] Forge

**Environment(s)** 

- [ ] Singleplayer
- [x] Server

**Versions**
* Minecraft 1.20.1
* Taterzens 1.11.7

**Comment by samolego** [comment]
> I wanted to change a NPC's type to villager

That's a disguiselib thing.
Merge is not happening, sorry.
