### ISSUE TITLE
Bug Report: Message Delay doesn't seem to be working [Fabric]

### ISSUE THREAD

**Issue by BokChewy** [samolego/Taterzens#176]
**Describe the bug**
Editing the message delay value in the config.json file of taterzens doesn't actually change the NPC messaging frequency. 

**Platform(s)**
- [x] Fabric (on forge 47.2.0 via the Sinytra connector mod)

**Environment(s)**
- [x] Server

**Versions**
* Minecraft 1.20.1
* Taterzens 1.11.7

**To Reproduce**
1. set value to literally anything other than 140 ticks
2. reset server
3. profit (every 140 ticks)

**Expected behavior**
I expected the message delay value to actually change how often the taterzen NPCs spit out messages.

**Comment by samolego** [comment]
Have you spawned the npc *before* or *after* editing the config?

**Comment by BokChewy** [comment]
Thanks for the suggestion, idk why I didn't think of that. Worked like a charm, sorry for wasting your time!

**Comment by samolego** [comment]
Np :)
