### ISSUE TITLE
The forge server use Sinytra Connector to add fabric version Taterzens

### ISSUE THREAD

**Issue by PokieeAngNown** [samolego/Taterzens#186]
When I use Sinytra Connector to add fabric version Taterzens 1.20
The server warn this:

[20:53:52][WARN][FabricLoader/Resolution]: Warnings were found!
SEmod "Taterzens’ (taterzens)$r 1.11.7 recommends version 1.2.1 or later of $6disguiselibgr, which is miss
You should install version 1.2.1 or later of §6disguiselib§r for the optimal experience.

The Disguiselib dosen't support 1.20.1
How to figure out this issue or when does the forge Taterzens 1.20 support

**Comment by samolego** [comment]
DisguiseLib is optional

**Comment by PokieeAngNown** [comment]
> DisguiseLib is optional

But I have never added this mod to my server

**Comment by samolego** [comment]
You don't need to add it.
