### ISSUE TITLE
Reconsider building against Java versions newer than 21

### ISSUE THREAD

**Issue by nelind3** [samolego/Taterzens#193]
I meant to try and catch this on the 1.21 PR but didn't manage to do so before it got merged so i figured making an issue would be appropriate.

As we all know one of the really major changes in 1.20.5 was the update from Java 17 to Java 21 as such mods built for anything post 1.20.5 will have to use Java 21 or newer. However realistically most people will run servers and the game with Java 21. The community at large expects everyone to run the game and build code against the minimum required Java version. Many setups for running the game (including the official launcher or the most used [docker image for Minecraft server software](https://github.com/itzg/docker-minecraft-server)) don't include built in functionality for running the game with any other version than the minimum required version (like the official launcher) or need specific support for it which is very low priority since it's generally not needed (like the docker image).

In #192 the build.gradle compatibility version was set to Java 22 and the CI configuration was changed to build released against Java 23. Since the JVM won't (for good reason) load classes that are built against a newer Java version doing this would effectively force every consumer of Taterzens to run their game on Java 23 or later. This would exclude many people from running or using Taterzens either because they use the vanilla launcher or because they for some other reason can't (or won't) use anything other than Java 21. I'd hate to see Taterzens not get used (and not be able to use it) simply because it's built against an unusual Java version.

Other than that I'd like you thank you all for the absolutely amazing work that you all have put into this project!! It's amazing to see projects like this that make fabric based servers a great option to choose!!

**Comment by samolego** [comment]
Hi! Thanks for the explanation and suggestion! If you have any spare time, feel free to PR it 😉

**Comment by nelind3** [comment]
Fixed by #194

**Comment by samolego** [comment]
Thank you so much!
