### ISSUE TITLE
NPC's not pathing

### ISSUE THREAD

**Issue by StripClubHero** [samolego/Taterzens#21]
As stated on Curseforge, when I set up an NPC with a path in my world, they refuse to go further than the first point set (which was 40 blocks away).  They will make their way to the block before and never actually step onto the path set block.  Just stares into that direction and never moves again.  I've tested this with multiple NPC's and on multiple blocks (slabs, full blocks, path blocks etc) and the result is always the same.  The NPC's were tested on a basic loop path 40 blocks between each point, and set to FORCED_PATH.

**Comment by KingOfCactus** [comment]
Same with me, this started to happen when i updated the mod to the 1.1.0 hotfix (forge).

**Comment by samolego** [comment]
Thanks for reporting! I don't think that it was hotfix that caused it but you never know.

**Comment by samolego** [comment]
https://user-images.githubusercontent.com/34912839/121515529-90e08f00-c9ed-11eb-8ee7-972587fb166f.mp4

Humm, seems to work fine here. Perhaps it is the distance ..?
