### ISSUE TITLE
NPC wont be invunerable!

### ISSUE THREAD

**Issue by 4Technic** [samolego/Taterzens#23]
The 1.16.5 Hotfix version wont allow me to set a NPC invunerablity to false. Am i missing something? Ive tried the Npc edit command
Thanks!

**Comment by James103** [comment]
Have you tried the following commands?
`/data modify entity @e[type=taterzens:npc,limit=1,sort=nearest] Invulnerable set value 0`
`/data merge entity @e[type=taterzens:npc,limit=1,sort=nearest] {Invulnerable:0b}`

Additionally, have you tried checking the Taterzen's data with the following commands?
`/data get entity @e[type=taterzens:npc,limit=1,sort=nearest]`, then look at the `Invulnerable` tag's value.
`/data get entity @e[type=taterzens:npc,limit=1,sort=nearest] Invulnerable`

**Comment by 4Technic** [comment]
Yes, Thank you it worked!!! Also, Just a suggestion, mabye make it so that you can change if NPCs can sprint and also if hostile mobs can attack that NPC.
THANKS THOUGH!!!

**Comment by 4Technic** [comment]
Also the abilitys for NPC's to heal would be nice

**Comment by samolego** [comment]
> also if hostile mobs can attack that NPC.

Mobs won't attack invulnerable entities, that's why suggestion pops up (to disable invulnerability) when changing behaviour to hostile.
