### ISSUE TITLE
GitHub does not allow `<script>` tags to be used properly.

### ISSUE THREAD

**Issue by James103** [samolego/Taterzens#33]
In https://github.com/samolego/Taterzens/blob/master/docs/config.md, there is a `<script>` tag which is required for the config to load properly. However, GitHub does not allow such `<script>` tags to be used properly, instead displaying the tag and whatever's inside as plain text.

Therefore, for the config file (using GitHub's view), you will need to hard code the output of whatever the included tag was supposed to do and manually update it whenever you make a new release.

Alternatively, you can direct people that want to view the documentation to the correct site to properly display the docs, such as https://samolego.github.io/Taterzens/1.2.0/config/.

**Comment by dbarnes18** [comment]
You're supposed to view it on the [site](https://samolego.github.io/Taterzens/1.2.0/config/)

**Comment by samolego** [comment]
There's already many links pointing to the website mentioned above plus adding another link will look strange for those browsing the web guide.
