### ISSUE TITLE
Taterzens disconnecting players when created/edited

### ISSUE THREAD

**Issue by Alkiasan** [samolego/Taterzens#37]
Whenever creating a Taterzen, players seem to be disconnected at random. Sometimes it chooses one player to disconnect, sometimes it disconnects everybody, and sometimes it only disconnects the person creating the NPC. Players do not have to be anywhere near the NPC to be disconnected. This same disconnect can also happen if the NPC has its skin changed, or whenever the player loads in the NPC serverside upon leaving and reentering the area.

The disconnect is extremely inconsistent, sometimes I can create 20 NPCs without a disconnect, and sometimes disconnects will happen upon the first NPC being created.

For example, if I get two alts on, Alt 1 and Alt 2, running the same exact mods with the same configs, and both in completely different areas in the world:

Alt 1 creates an NPC, Alt 2 gets disconnected.
Alt 2 creates an NPC, Alt 1 does not get disconnected.
Alt 1 creates an NPC again, this time, Alt 2 does not disconnect.

Additionally, while an NPC is on the server, clientside logs get spammed with this error:
![image](https://user-images.githubusercontent.com/62717881/127035621-74c1c2ee-b698-4b79-9467-62977fb6d645.png)

Here's the error that happens upon disconnect clientside:
https://gist.github.com/Alkiasan/879521c75661ff644af406b8491106d1

And here's the error that happens upon changing an NPC's skin causing a disconnect:
https://gist.github.com/Alkiasan/7679d0928a95a92d856e13f30baea96e

We're running Taterzens 1.1.0 on fabric 1.16.5 (loader 0.11.6)

Hopefully there's a way to find a fix for this, sadly it makes the mod unusable on some servers...

**Comment by samolego** [comment]
Thanks for excessive report, I'll have a look when I have time, although I doubt that there'll be a fix for 1.16

**Comment by Alkiasan** [comment]
That's a shame, we can't update to 1.17 since most of our core mods still haven't updated.
Thanks for looking into it, though!

**Comment by Alkiasan** [comment]
Small update, but here's a de-obfuscated version of this error.
https://gist.github.com/Alkiasan/3f71de6204ecb37ceb9d56ac0a01efe2

**Comment by Alkiasan** [comment]
The error is spammed clientside constantly, even when not disconnected. 5 minutes of playtime results in around 1,500 "Fatal" errors.

**Comment by James103** [comment]
> The error is spammed clientside constantly, even when not disconnected. 5 minutes of playtime results in around 1,500 "Fatal" errors.

In other words, while a Taterzen is loaded into the world, the log size (on client side) increases by 10 KB per second because of this issue. After 1 hour, that already results in a log file that is 36 MB in size (uncompressed).

**Comment by Alkiasan** [comment]
> > The error is spammed clientside constantly, even when not disconnected. 5 minutes of playtime results in around 1,500 "Fatal" errors.
> 
> In other words, while a Taterzen is loaded into the world, the log size (on client side) increases by 10 KB per second because of this issue. After 1 hour, that already results in a log file that is 36 MB in size (uncompressed).

Yeah. It tends to cause lagspikes on lower-end PCs too whenever an NPC loads/unloads... In other words, the mod is essentially usable in 1.16.5 without errors and issues. I am unsure on whether or not this issue exists on 1.17, since I have been unable to update yet.

**Comment by samolego** [comment]
Yeah, sorry for lack of my comments here, this has been fixed quite a long time ago, although I'm not sure if it's available for 1.16

**Comment by samolego** [comment]
Yep, it's 1.2.0, available for 1.17

**Comment by Alkiasan** [comment]
It's a lot to ask, but is there any chance of this fix being ported to 1.16 in the future?
