### ISSUE TITLE
Book and Quill won't save book Title

### ISSUE THREAD

**Issue by Astraica** [samolego/Taterzens#42]
I can't make a written book with this mod running. I've done absolutely nothing with it in this version I've got running, so I'm unsure what it is, I've literally just dropped the mod in my mods folder, ran it, closed, ran again and played.

**Comment by samolego** [comment]
Can you reproduce the issue without other mods if using any? Which platform? Any (strange) log reports?

**Comment by Astraica** [comment]
It works fine without any other mod, am testing with one mod then adding in the others, I only had WorldEdit, Ambiance Extras, Optifine, warpmod, and OfflineSkins. I think it's Ambiance though sec.

**Comment by Astraica** [comment]
Hrmn... I've completely re-created the problem and it works fine... I'm not sure what happened, it must have been something on my computer's end.
