### ISSUE TITLE
skins not showing up

### ISSUE THREAD

**Issue by aelianix** [samolego/Taterzens#43]
i'm using the latest fabric 1.16.5 version, and I'm finding that when I use /npc edit skin (username), the skins only show up if i've played with the username's account recently, is that supposed to happen?

**Comment by samolego** [comment]
Humm, no, it's not supposed to be like that. Singleplayer env? / Do you have valid internet connection?

**Comment by aelianix** [comment]
i figured it all out! my school's internet apparently interfered with the skin grabbing stuff, but my home internet let it work :)
