### ISSUE TITLE
CarryOn incompatibility/crash

### ISSUE THREAD

**Issue by SkullDiamond** [samolego/Taterzens#46]
[crash-2021-09-10_17.05.10-client.txt](https://github.com/samolego/Taterzens/files/7144703/crash-2021-09-10_17.05.10-client.txt)

**Comment by samolego** [comment]
Thanks for report!

**Comment by samolego** [comment]
Totally forgot about this issue; this is causing it https://github.com/samolego/Taterzens/blob/0cc57fe9f05f94411ba98932a8bcd6429445965c/common/src/main/java/org/samo_lego/taterzens/npc/TaterzenNPC.java#L194

Should be a trivial fix
