### ISSUE TITLE
Commands on Taterzens duplicate upon logging in (fabric MC1.17.1)

### ISSUE THREAD

**Issue by Timdeuces** [samolego/Taterzens#49]
Sometimes when I log into my world, the command on my Taterzen has been duplicated, sometimes several times, so I have to clear the list and input the command again each time. I've been attempting to find steps to reproduce, but it seems to only happen sometimes, without any predictability.
![image](https://user-images.githubusercontent.com/21376973/133105684-e3475492-ec8e-4e78-b6cd-9b4761245845.png)
I have also noticed that sometimes when doing data changes on the entity with the /data command, or attempting to mount, the game starts chugging really hard, or freezes as if it's trying to resolve something but can't, so I have to use task manager to close it.

**Comment by samolego** [comment]
Are you using any other mods? Can you send me the taterzen preset (`/npc preset save`)?

**Comment by Timdeuces** [comment]
> Are you using any other mods? Can you send me the taterzen preset (`/npc preset save`)?

I'm also using Dynamic Sound Filters, Mod Menu,  and Optifabric with the latest Optifine

preset:
https://www.dropbox.com/s/tf5hzuzwyb14a1w/daisy.json?dl=0

**Comment by CruxCraft** [comment]
@Timdeuces could it be only when you restart the server? I was/am having what turns out to be the same issue I think, and upon testing, they double in quantity after a server restart. I tried recreating by just disconnecting and re-joining and it didn't happen. I was able to recreate once from a config reload, never from a disconnect, and every time after a server restart. (up to 128 now)

**Comment by samolego** [comment]
Humm, I cannot seem to reproduce this, even though I easily reproduced #51 ...

**Comment by Timdeuces** [comment]
> @Timdeuces could it be only when you restart the server? I was/am having what turns out to be the same issue I think, and upon testing, they double in quantity after a server restart. I tried recreating by just disconnecting and re-joining and it didn't happen. I was able to recreate once from a config reload, never from a disconnect, and every time after a server restart. (up to 128 now)
> 
> EDIT: I saw that you mentioned Optifine, so this this only in a single-player world that you have the Taterzens/NPCs?

It is singleplayer. It seems to have stopped now that I got rid of Mod Menu. My hunch is that it occasionally does something to mess with the config files, which might trigger a reset like you described.
