### ISSUE TITLE
Bungee commands aren't listed and also seem to be running 500+ times per use

### ISSUE THREAD

**Issue by CruxCraft** [samolego/Taterzens#51]
/npc edit commands list 
doesnt show any commands
I know previously it would show non-bungee commands, not sure if it still does, but it definitely is not listing the bungee command that is added to change the server

Also, it seems as though the NPC runs the command 500+ times as I am now getting "You are already trying to connect to a server!" with +1500 pending lines of the same thing from using 3 NPCs. manually typing /server server_name does not result in this, only using the NPC to run the command. Restarting server, the client, or the proxy unfortunately don't seem to be stopping the pending lines... I don't even want to click on another one because I still have ~980  pending lines to get through...

this was not happening before I issued the command:
/npc edit messages clear
not sure if it is related, but this started happening after clearing the messages on an NPC (which is why I was running /npc edit commands to try and see what was going on after that)

**Comment by CruxCraft** [comment]
I decided to test it again anyway since I had restarted client, server, & proxy to see if it self fixed... it added an additional 5,000 this time!! I am currently waiting for ~4,800 pending lines

**Comment by CruxCraft** [comment]
this is every NPC now too btw, not just the one that had the messages cleared

**Comment by samolego** [comment]
Huh, this is strange, it didn't happen while testing. For bungee commands, they should have negative index.

Could you check the preset file of the taterzen?

**Comment by CruxCraft** [comment]
The presets directory is empty, the permissions.toml is untouched, and I believe the only thing changed in the config.json was this:

  "bungee": {
    "// Whether to enable bungee commands feature fo NPCs.": "",
    "enable_commands": true,
    "// Bungee servers to be listed in command suggestions.": "",
    "servers": [,
      "Lobby",
      "server1",
      "server2",
      "server3",
      "server4",
      "server5",
      "server77"
    ]
  }
}

one of the config reloads I had an extra comma that I had to remove. I ran it through a json validator now too to make sure it was valid json

I will delete(rename) the config directory, then enable bungee commands again to see if it self fixes
where are the NPCs & commands stored? I noticed the entities still exist even without the plugin so are saved in game, so maybe stored there outside of reach?

If removing the config doesnt work I will try removing NPCs next and try a new NPC as well

**Comment by CruxCraft** [comment]
FYI:

adding a NEW NPC
/npc edit commands addBungee server --clicker-- serverX

did NOT add the extras

then I clicked on old one and it added 10,000 this time

**Comment by CruxCraft** [comment]
REMOVING the old config directory made all the pending lines go away and I have re-enabled bungee(velocity) commands and we seem all good... I am going to copy the exact same config that was in there before now and see if it is that

SO VERY GLAD all those 15,000 pending lines are gone lol

**Comment by CruxCraft** [comment]
added the exact same config in as before, not having that same issue, so I am guessing having bungee set to false temporarily removed whatever the problem was

/npc edit commands list
now shows the bungee commands

some NPCs are getting the same command added multiple times

one of them did something really really weird; it had a duplicate command so I ran this:
/npc edit commands remove -2
then when running /npc edit commands list
it had 3X after removing the duplicate
I was able to remove both of the duplicates, but it is strange unintended behavior

**Comment by CruxCraft** [comment]
/taterzens config reload

this command is duplicating the NPC commands

**Comment by CruxCraft** [comment]
I doubled it all the way to 512 before it stopped listing them
![Screenshot from 2021-09-14 12-44-19](https://user-images.githubusercontent.com/56696312/133323742-2cff2de6-da95-4d89-88bb-a5c6c0897570.png)

**Comment by CruxCraft** [comment]
just sharing this process for anyone who needs to remove a long list of bungee(velocity) commands from an NPC

- edit config.json
-     "enable_commands": false,
- then restart the server (reloading config will not remove the commands)
- edit config.json
-     "enable_commands": true,
- /taterzens config reload
- now put back in whatever addBungee commands you want
