### ISSUE TITLE
Error loading this mod :/

### ISSUE THREAD

**Issue by Stonksmannnn** [samolego/Taterzens#61]
Hey, i put Taterzens mod on mod folder, launch the game. Then this message :

Taterzen (taterzen) has failed to load correctly
java.lang.reflect.invocationTargetException : null

**Platform(s)**
PC

- [x] Forge 1.17.1-forge-37.0.84

**Environment(s)** 

- [x] Singleplayer

**Versions**
* Minecraft 1.17.1
* Taterzens 1.4.1

**To Reproduce**
1. Launch forge single player minecraft
2. See error :
             "Error loading mods
1 error has occured during loading"                 

**Expected behavior**
Launch the game my mods normaly 

**Logs**

Latest.log : https://mclo.gs/UvQiurY
Crash.txt (if needed) : https://mclo.gs/o7zHrvI

- PS : I have a question please, i download this mod to create a NPC farmer because my farmers want to go in base when they are on a automatic plateform farm. Is it possible with this mod to just create a simple farmer who dont care about go home and just farm a closed area ? 

Thanks for the mods btw, very professionnal. Im a pretty new player at minecraft and im amazed by talented modders on this game. Thanks again samolego

Sry for my poor english btw 

EDIT : Taterzens 1.4.0 work just for you to know

**Comment by samolego** [comment]
Fixed in 1.4.2
