### ISSUE TITLE
Skins "fetched" but staying the same

### ISSUE THREAD

**Issue by CloakTheWhat** [samolego/Taterzens#62]
**Describe the bug**
Despite the skin was fetched, the skin did not change at all

**Platform(s)**

- [x] Forge

**Environment(s)**

- [x] Server

**Versions**
* Minecraft 1.17.1
* Taterzens 1.4.2

**To Reproduce**
1. Launch server
2. Run
3. Create an npc
4. edit the skin
5. Nothing changes

**Expected behavior**
Skin of the npc would change with the use of a Mineskin url or a player name

**Additional context**

**Comment by samolego** [comment]
I'm not able to reproduce this with taterzens only in this release. It must be a mod conflict if it is still there.
