### ISSUE TITLE
Bug related to 1.6.0 and Messages (maybe) [Fabric]

### ISSUE THREAD

**Issue by MinecraftMoments** [samolego/Taterzens#63]
**Describe the bug**
Most things work wonderfully, but I was editing messages, and while editing messages in my world, the game freezes. I cannot send messages, and if I'm in the GUI for the NPC, it grabs the menu options as regular items. I'm assuming something causes a massive lag spike. I also don't seem to be able to save my world, as it just gets stuck on "Saving World" and I have to use the task manager to kill the game.

**Platform(s)**
I've only tested it on Fabric, as I only use fabric, so I do not know if this is the same on Forge.

**Environment(s)**
I was playing in singleplayer.

**Versions**
* Minecraft 1.17.1
* Taterzens 1.6.0

**To Reproduce**
- Open up a Minecraft world with the mod
- Edit a Taterzens messages
- After interacting with the editing, game stops responding properly / freezing up

**Expected behavior**
For... It not to freeze and to continue to work, I guess?

**Logs**
Unfortunately, it does freeze it in a way that doesn't produce any log errors, as far as I am aware. It simply freezes the MultiMC log at the last message it loaded before it started to lag, and nothing else is recorded.  

**Additional context**
It was working fine before this, and I haven't messed around with 1.5.0 a lot, but downloading it seems to be running pretty well compared to 1.6.0, although I definitely do adore the GUI. (Then again, I also downloaded it not long after the release, since I was searching for an NPC mod for Fabric just today, and found this one)
There may be some incompatibilities with my other mods and 1.6.0, but I've been idling in 1.5.0 and it seems to work smoothly. So, I don't know.
I hope this report helps!

**Comment by MinecraftMoments** [comment]
This is NOT related to the above issue, but I DO want to note that the commands are very intuitive and they feel very nice and easy to understand, and so does the GUI, even if it's a little confusing at first.
Also, the fact that it works with Fabrictailor, another mod I looked for and found pretty easily today, makes me SO happy! <3

**Comment by samolego** [comment]
Hi, thanks for reporting!
Can you provide some more details:
1. Was taterzen a frehsly spawned one / did it have any messages before editing?
2. Does the freeze occur when sending the new / edited message?

**Comment by samolego** [comment]
Could you try [this](https://github.com/samolego/Taterzens/actions/runs/1438743932) build and see if the error is still there?

**Comment by MinecraftMoments** [comment]
VERY late response, as we went to sleep and got distracted, but I will test out the build now! 
1. It was spawned a bit before I edited the messages (i'd say I was editing for 10 mins?? ish?? not Very long but not Just spawned in? i guess?), and it did not previously have messages, I was adding them in and it froze.
2. I do not know if you meant that the freeze occurred when the taterzen was sending messages or if it occurred when I was sending messages, but I was messing around with the 1.5.0 version and it endlessly sends the messages. The 1.6.0 version sends around 4-5 messages before something starts going Wrong

Testing the new build (the one in the folder simply titled 1.6.0 fabric, from the artifacts, lmk if I needed to test another .jar file): It doesn't seem to crash, but it "adds" messages and then the taterzen doesn't repeat them with the loop. Re-entering the world doesn't seem to fix the issue. (Image Below)
![image](https://user-images.githubusercontent.com/84159674/140937580-00398820-bb4f-4c6e-9b52-3ba9d7f7e299.png)
I only had those four messages on the 1.5.0 build, and the accidentally-duplicated messages were messages I didn't think the game "saved". 

Gonna test the world copy on the 1.5.0 build for a minute, and it did not show the "added" messages, as if they weren't added in the first place. 
![image](https://user-images.githubusercontent.com/84159674/140939689-afb079c9-bb5e-4442-80ef-02ffdca30967.png)
I was able to add other messages and they worked wonderfully, though! Only on 1.5.0.

If there's anything else you might need to know to help with this, or if you'd like me to beta-test more n see if things work/don't work. Also, just in case it matters, here's a list of all the mods I have active right now.
![image](https://user-images.githubusercontent.com/84159674/140940038-f16285ca-03ad-47cb-98de-78e0e8b93992.png)
(Mostly adding this to the comment in case there are known incompatibilities, though it works just fine with 1.5.0 with all these mods. And yeah, it says 1.5.0 but i've swapped 1.6.0 out with the older version that is currently on (and im probably gonna play with some more)

**Comment by samolego** [comment]
Regarding
> Testing the new build (the one in the folder simply titled 1.6.0 fabric, from the artifacts, lmk if I needed to test another .jar file): It doesn't seem to crash, but it "adds" messages and then the taterzen doesn't repeat them with the loop. Re-entering the world doesn't seem to fix the issue. (Image Below)

Have you exited the message editor after you finished sending mesaages? Messages are not sent if you stay in editor (in order not to disturb you while putting messages in)
To sum it up, the latest dev version worked fine (apart from that above)?

**Comment by MinecraftMoments** [comment]
> Have you exited the message editor after you finished sending mesaages? Messages are not sent if you stay in editor (in order not to disturb you while putting messages in)

I did (you can see the pink text reading "you exited the editor" and the taterzen repeating the og text, but not adding in the text it shows as listed.)
Also, yes, it seemed to not bug besides the not saving the messages issue!

**Comment by samolego** [comment]
Are you able to reproduce this in 1.6.1?

**Comment by MinecraftMoments** [comment]
At first, I thought you meant 1.16.1, but I will test it in a moment.
It seems to be fixed, yeah!
![image](https://user-images.githubusercontent.com/84159674/142332988-03066c93-c214-4473-96c7-1e9de1c1ccde.png)
I can't wait to use this mod more now!

(Also, apologies for the late reply!)
