### ISSUE TITLE
Sitting pose

### ISSUE THREAD

**Issue by CoreBytee** [samolego/Taterzens#64]
**Describe the bug**
You can set poses using `/npc edit pose ...` and i wanted to let my NPC sit, but there is no pose for that :/

**Platform(s)**
- [x] Fabric

**Environment(s)**
- [x] Singleplayer
- [x] Server

**Versions**
* Minecraft 1.17.1
* Taterzens 1.6.0

**To Reproduce**
Type `/npc pose sit(ting)` in chat with a npc selected
There is no sitting pose

**Comment by samolego** [comment]
That's a feature request then :P ...

You can create an invisible armor stand and make npc mount it.

**Comment by CoreBytee** [comment]
Yea that's a feature request :D

_You can create an invisible armor stand and make npc mount it._
Okay i will try

Thanks for your help, amazing mod as always :P
