### ISSUE TITLE
Cannot use command edit POSE

### ISSUE THREAD

**Issue by RafelAlva** [samolego/Taterzens#65]
**Describe the bug**
the command /npc edit pose is not there

**Platform(s)**

- [x] Forge

**Environment(s)**

- [x] Server
- [x] Single Player

**Versions**
* Minecraft 1.16.5
* Taterzens 1.1.0 HOTFIX

**To Reproduce**
1. Launch server
2. create npc with /npc create (nickname)
3. proceed to run command /npc edit pose
4. there are no "pose" command to be seen

**Expected behavior**
i expected there to be edit pose command for the npc

**Comment by samolego** [comment]
Install the latest version.

**Comment by RafelAlva** [comment]
ok. but is there any latest version for 1.16.5? becuz i have modpacks i arranged myself that only worked in 1.16.5. using 1.17.1 means that i have to leave all that just for taterzen

**Comment by RafelAlva** [comment]
> Install the latest version.
ok. but is there any latest version for 1.16.5? becuz i have modpacks i arranged myself that only worked in 1.16.5. using 1.17.1 means that i have to leave all that just for taterzen

**Comment by samolego** [comment]
Well, look in the releases :) ... What I wanted to say is that new features are not backported.

**Comment by samolego** [comment]
Yeah, 1.10 is latest for forge 1.16.5 :\
