### ISSUE TITLE
Bug report [Forge]

### ISSUE THREAD

**Issue by johnnyjmcivorv** [samolego/Taterzens#67]
Hi, I tried installing the NPC mod for forge (Minecraft 1.18). I put the jar in my mods folder and booted it up. I got this error on bootup

https://i.imgur.com/dyhaNan.png

Thank you!

**Comment by samolego** [comment]
Thanks for report. Could you try installing the mod from "artifacts" [here](https://github.com/samolego/Taterzens/actions/runs/1548640038) (just unzip the file and place jar in `mods/`)

**Comment by johnnyjmcivorv** [comment]
Hi, so I placed the "taterzens-1.6.4-forge" jar into my mods folder and it loaded up (dropping the whole folder in there did not load it up).

I have started using it and this menu does not seem to work

https://i.imgur.com/TeyEyGO.png

I drag / click on the icon I want and it does not do anything.

**Comment by samolego** [comment]
You have to set the invulnerability to false.
Regarding menu, it's a new issue, so I'm closing this one.

You have to reselect npc after leaving the world / being killed etc. You can remove it with `/kill @e[type=taterzens:npc,limit=1]` or simply `/npc remove`
