### ISSUE TITLE
GUI doesnt work at all

### ISSUE THREAD

**Issue by nekomaster** [samolego/Taterzens#68]
MC 1.18.1
Forge 39.0.5
Taterzens 1.6.4-forge-fixed

GUI doesnt work, buttons do nothing, can only close the GUI with ESCape key

Right clicking on the NPC's brings up an inventory style GUI with buttons that look like items. Left or right clicking on stuff as well as trying keyboard modifiers like SHIFT or CTRL when clicking does nothing at all.

No other mods are loaded. I've included some logs just incase this helps at all.

[latest.log](https://github.com/samolego/Taterzens/files/7730409/latest.log)
[debug.log](https://github.com/samolego/Taterzens/files/7730410/debug.log)

**Comment by samolego** [comment]
Thanks for report, I'm already aware of this and trying to fix it :)

**Comment by samolego** [comment]
Fixed in 1.6.5
