### ISSUE TITLE
Compat issue (ctd, Identity)

### ISSUE THREAD

**Issue by codegavran** [samolego/Taterzens#7]
Running Identity 1.12 and Taterzens 1.0, trying to open the identity gui causes a ctd.

I'm not familiar enough with MC mod dev to troubleshoot really, but it's almost certainly a compatibility issue between the two mods.

Crash log: https://pastebin.com/Sm3Mh1Jc

Identity Issue Tracker x-post: https://github.com/Draylar/identity/issues/183

**Comment by samolego** [comment]
Ah, yeah, I see, TaterzenNPC constructor assumes that the world's server is not null.

**Comment by codegavran** [comment]
Dang, you found that fast! :D Can ya just give it an exception handler and it'll work or is it more complicated than that?

**Comment by samolego** [comment]
I'll see. First I have to find out how Identity works. :)

**Comment by samolego** [comment]
Diving into this now; Taterzens just specify a PlayerEntity renderer (just to prevent crashes as it is actually not needed, because the mod operates server-side only), which in this case isn't applicable.

**Comment by samolego** [comment]
![image](https://user-images.githubusercontent.com/34912839/115760740-d4c9f700-a3a1-11eb-9fd0-48e5984e0140.png)
Fixed :)
