### ISSUE TITLE
Commands without clicking

### ISSUE THREAD

**Issue by Jzorreguiet** [samolego/Taterzens#71]
Hi, I've been trying this mod in my modpack (something that I would like to know if I'm allowed to publish somewhere or not) and I'm trying to use some commands without having to click the NPC, but I don't know if it's possible. Is there any way to do that?

**Comment by James103** [comment]
> I'm trying to use some commands without having to click the NPC, but I don't know if it's possible. Is there any way to do that?

You could use custom scripts with Carpet mod (which can do much more than just run commands), as described here:
https://samolego.github.io/Taterzens/1.6.5/professions/scarpet_profession/

However, that means Carpet mod would need to be in your mod pack (at least on the server-side).

**Comment by samolego** [comment]
As James mentioned above, the easiest way to do it would be woth carpet scripting.
See https://github.com/samolego/TaterzenScarpetProfessions#available-events for the events, you'd probably be interested in
```
__on_taterzen_approached_by
```
which triggers every tick when players are nearby.

Alternatively you could code a profession, although that requires java knowledge and is harder than scripting.

Of course you can include the mod in pack, it's MIT licensed :).

**Comment by Jzorreguiet** [comment]
Thanks! however, it says that it's only available on Fabric, but I'm on Forge

**Comment by samolego** [comment]
Ah, that would require you to code it using java then ...
