### ISSUE TITLE
GUI not working [Forge]

### ISSUE THREAD

**Issue by Jissee** [samolego/Taterzens#73]
**Describe the bug**
I just don't know how to work with taterzens mod in some aspects.

**Platform(s)**

- [x] Forge 39.0.14

**Environment(s)**

- [x] Server

**Versions**
* Minecraft 1.18.1
* Taterzens 1.8.0

**To Reproduce**
1. Launch server and client
2. Connect to the server
3. Input command "/npc create Dream"
4. A npc was created, but it had a "glowing" effect and I didn't know how to remove it.
5. Right clicked the npc, a gui menu appeared.
6. Left clicked or right clicked the icons in the menu, nothing changed.

**Expected behavior**
I expect that the character will not be glowing when it is created, and we can add or remove the effects.
Maybe the gui menu fail to work on this version. Please check it. Thank you!

**Comment by samolego** [comment]
Npc glowing is normal, it just shows you which npc is selected (only you can see it while in multiplayer). It's reset after rejoining a world / server or deselecting (`/npc deselect`).

I'll have to take a look in GUI though.

**Comment by samolego** [comment]
Also see docs https://samolego.github.io/Taterzens/1.8.0/

**Comment by Jissee** [comment]
> Also see docs https://samolego.github.io/Taterzens/1.8.0/

Thanks for your concern. However, the doc page has a large "taterzens" logo and it results in a large menu bar, which occupies more than half of the page. (like this) Are there some troubles with my browser?
![png](https://user-images.githubusercontent.com/50765103/148786103-c4ec1d75-a100-4992-a846-ca13ed78d59d.png)
Are there any troubles with my browser?

**Comment by samolego** [comment]
Humm, that's strange, works fine here, tried Brave (Chromium) and Firefox
