### ISSUE TITLE
Inventory emptied [Forge]

### ISSUE THREAD

**Issue by Jissee** [samolego/Taterzens#74]
**Describe the bug**
I am sorry to inform you of another bug that was just found. The GUI menu can empty my inventory.

**Platform(s)**

- [x] Forge 39.0.18

**Environment(s)**

- [x] Server

**Versions**
* Minecraft 1.18.1
* Taterzens 1.8.0

**To Reproduce**
1. Launch server and client.
2. Connect to the server.
3. Switch my own gamemode to "creative".
4. Add some blocks and items to my inventory.
5. Summon an NPC with the command "/npc create Dream". An NPC with a green appearance and a smiling face appears which is selected(glowing).
6. Right click the NPC and a GUI menu appears. Meanwhile, everything in my inventory is gone.
7. Deselect the NPC and try the same steps again. The menu doesn't appear and the command set on the NPC can function correctly. And nothing in my inventory is changed.

**Expected behavior**
I don't think the GUI menu should empty my inventory. And maybe menus of editing and creating an NPC can be a little different to be compatible with different functions.

**Comment by samolego** [comment]
Tested it yesterday, it's another one of those nasty bugs that apper in production, but not while testing :|

**Comment by samolego** [comment]
Anyway, GUI not working is #73 , so I'm closing this.
