### ISSUE TITLE
npc removal by custom tags eg: /kill @e[type=taterzens:npc,name=<name>]

### ISSUE THREAD

**Issue by thecounter89** [samolego/Taterzens#78]
im making a map with npcs and creating npc's w presets through command blocks works fine but i can't find any way to remove them through a command block. if there's a known solution to this or way to make it possible that would be great.
i tried /kill @e[type=taterzens:npc,name=<name>] using the name of the npc i want to remove and made sure it is not invulnerable but it does not work. also tried using the /npc remove w the npc i want to remove selected but that doesnt work in a command block

**Comment by samolego** [comment]
Just do /kill @e[type=taterzens:npc] without empty name and use distance modifier?

**Comment by thecounter89** [comment]
thanks, i was using names with spaces too so it couldnt recognize them properly even when using _ replacing the spaces in their names with -  and using the command seemed to fix it. i dont know if there is a solution to names with spaces

**Comment by samolego** [comment]
Try using quotes, e.g. name="My Taterzen". Otherwise try to ask in e.g. minecraft commands discord ;)
