### ISSUE TITLE
some problems with MrCrayfish's Gun Mod[Forge]

### ISSUE THREAD

**Issue by bucketBrian** [samolego/Taterzens#82]
**Describe the bug**
1.unable to equip "MrCrayfish's Gun Mod" 's Guns to NPC
2.unable to summon NPCs  which equip Guns with Attachments

**Platform(s)**
1.18.1-Forge_39.0.79

**Environment(s)**
Singleplayer

**Versions**
* Minecraft 1.18.1
* Taterzens 1.8.4
* MrCrayfish's Gun Mod 1.1.3

**To Reproduce**
problem 1:
1. get into the game.
2. create an NPC.
3. get into the equipment mode, then hold the Guns and right click to NPC.
4. the NPC won't equip the gun. (this will only happen to guns (I didn't test all of them), rest of the item from this mod will be work fine.

problem 2:
1. create a NPC preset
2. open the correspond json file, to the "HandItems" setting and input the code for the Guns with Attachments(it will works fine if don't add any NBT or just with "AmmoCount"). example: cgm:pistol{AmmoCount: 15, Attachments: {Scope: {id: "", Count: 1b}, Barrel: {id: "", Count: 1b}}, Color: 15961002}.
3. save, and go back to game. use command to summon preset NPC.
4. it will show a red text said similar to "unknown error occur".

**Expected behavior**
as describe above in each last step.

**Logs**
N/A

**Additional context**
N/A

**Comment by samolego** [comment]
What does it say when you hover over the preset error?

**Comment by bucketBrian** [comment]
![2022-02-22_02 40 43](https://user-images.githubusercontent.com/48875131/155011215-a70286c6-47b0-49dc-b4f8-d581c8e5cfbc.png)
this is the preset json I tested.
[1.zip](https://github.com/samolego/Taterzens/files/8111518/1.zip)

**Comment by samolego** [comment]
The preset file is corrupted, have you escaped " with \ properly?
E.g. id: \"\"

**Comment by bucketBrian** [comment]
the preset file is work, but there was a new problem, the summoned NPC 's Gun is _lost_, I use the /data command and it shows that they doesn't have anything on its hands

**Comment by samolego** [comment]
We're back to the first problem then ... It might be that gun items operate differently

**Comment by bucketBrian** [comment]
I'm think so, right click will let player aiming, it might because it's overwrite the operation of "use".

**Comment by samolego** [comment]
Can other mobs (e.g. Zombies & Skeletons) use guns?

**Comment by bucketBrian** [comment]
I can't summon mobs with "Gun+Attachments",  guns with no Attachments will work fine.
but mobs can collect "Gun+Attachments", at least I seen fox can do that.

**Comment by bucketBrian** [comment]
it should be relate to summon command, because I can equip the guns(with Attachment) by "item" command.

**Comment by samolego** [comment]
Does `/item replace entity <taterzen>` work then? Or have you only checked other mobs?
