### ISSUE TITLE
NPCs clump together and slow down when pathing/collision does not work

### ISSUE THREAD

**Issue by 4P5** [samolego/Taterzens#84]
**Describe the bug**
When two Taterzens are given the same goal (e.g., following a player or going to a location), they clump together into a single body and slow down. Example: https://i.imgur.com/YHpMQte.mp4

**Platform(s)**

- [x] Fabric

**Environment(s)**

- [x] Singleplayer
- [x] Server

**Versions**
* Minecraft 1.18.1
* Taterzens 1.8.4

**To Reproduce**
1. Spawn a few Taterzens and set them to follow you
2. Direct them so they occupy the same path

**Expected behavior**
I'd expect them to either push one another apart (i.e., not clump together), or to not be extremely slow.

**Additional context**
I have quite a few other mods installed, though I tried removing all bar this and nothing changed.

**Comment by samolego** [comment]
This is definetely weird. Thanks for report.

**Comment by samolego** [comment]
Have you tried changing their collision?

**Comment by samolego** [comment]
I think that `pushable = true` might work.

**Comment by 4P5** [comment]
I've tried that, as well as setting their shared team's collision rule to different things. It's strange as I haven't had that behavior before with this mod—are you able to reproduce the bug?

**Comment by samolego** [comment]
I'll try to reproduce it this week. Kinda busy atm.

**Comment by samolego** [comment]
/execute as @e[type=taterzens:npc] run npc edit tags pushable true

This has worked for me.
