### ISSUE TITLE
[Repo] `docs/support.md` is suggested by Github as a way of getting support

### ISSUE THREAD

**Issue by altrisi** [samolego/Taterzens#85]
Seems like that file is one of those from the `docs` folder that Github suggests in some cases, for example to users who have never created an issue or pull request.

That page doesn't contain what users would expect from that popup and looks broken on github's markdown viewer.

![imagen](https://user-images.githubusercontent.com/17107132/157525851-5c6b674d-5a2b-4daf-9b54-6360d329c1af.png)

**Comment by samolego** [comment]
Huh, seems like an automatic feature by GitHub. I could create a file since docs is already present.
