### ISSUE TITLE
Bug report [Forge / Fabric]: Looking at player crash

### ISSUE THREAD

**Issue by Flemmli97** [samolego/Taterzens#87]
**Describe the bug**
The "looking at target" thing of an npc causes a crash.
Caused by [https://github.com/samolego/Taterzens/blob/master/common/src/main/java/org/samo_lego/taterzens/npc/TaterzenNPC.java#L502](https://github.com/samolego/Taterzens/blob/master/common/src/main/java/org/samo_lego/taterzens/npc/TaterzenNPC.java#L502)
since the check doesn't cover an empty list properly.

**Platform(s)**

- [x] Fabric

**Environment(s)**

- [x] Server

**Versions**
* Minecraft 1.18.2
* Taterzens 1.8.5

**To Reproduce**
1. Launch server
2. Have an npc thats set to look at the nearest player
3. Walk away

**Expected behavior**
No crash

**Logs**

[https://pastebin.com/w5UzjUhE](https://pastebin.com/w5UzjUhE)

**Comment by samolego** [comment]
Thanks for reporting!
