### ISSUE TITLE
Getting kicked from server when using /npc create

### ISSUE THREAD

**Issue by DillonB07** [samolego/Taterzens#9]
I think the title says it all.
Latest release at time of posting with these mods:
<img width="438" alt="Screenshot 2021-04-23 at 18 23 26" src="https://user-images.githubusercontent.com/59509438/115907587-005fe680-a461-11eb-863a-b9affc17d8e9.png">
<img width="427" alt="Screenshot 2021-04-23 at 18 23 36" src="https://user-images.githubusercontent.com/59509438/115907599-0655c780-a461-11eb-9d7c-002c13162a9e.png">

**Comment by DillonB07** [comment]
23.04 17:20:55 [Server] Server thread/INFO Player Dillonia used command: /npc create Dillonia in minecraft:overworld
23.04 17:20:55 [Server] Netty Epoll Server IO #6/ERROR java.lang.NullPointerException
23.04 17:20:55 [Server] Netty Epoll Server IO #6/ERROR java.lang.NullPointerException
23.04 17:20:55 [Server] Netty Epoll Server IO #6/ERROR java.lang.NullPointerException
23.04 17:20:55 [Server] Netty Epoll Server IO #6/ERROR java.lang.NullPointerException
23.04 17:20:55 [Server] Netty Epoll Server IO #6/ERROR java.lang.NullPointerException
23.04 17:20:55 [Server] Netty Epoll Server IO #6/ERROR java.lang.NullPointerException
23.04 17:20:55 [Server] Netty Epoll Server IO #6/ERROR java.lang.NullPointerException
23.04 17:20:55 [Disconnect] User NOTTAVINCI has disconnected, reason: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException
23.04 17:20:55 [Server] Server thread/INFO Dillonia left the game

**Comment by samolego** [comment]
Humm, could you perhaps add Gunpowder as it contains a mixin which stacktraces netty errors?
As this log isn't really useful ...

**Comment by DillonB07** [comment]
No, I can't do that as Gunpowder conflicts with Carpet Mod(We need carpet)
Sorry.

**Comment by DillonB07** [comment]
It has to be a mod conflict but I can't think which one it could be...

**Comment by samolego** [comment]
Yeah, that's for sure. Perhaps setup a temp server with gunpowder utils instead of carpet or try adding mods and see when it occurs ...

**Comment by DillonB07** [comment]
What host do you suggest using for that?
Ideally one that I can add files myself(so not Aternos)
And is free+ Fabric.
Doesn't need to be 24/7 though

**Comment by DillonB07** [comment]
What host do you suggest using for that?
Ideally one that I can add files myself(so not Aternos)
And is free+ Fabric.
Doesn't need to be 24/7 though

**Comment by samolego** [comment]
Well, at the end of the day, you can try this with local server / even singleplayer ...

**Comment by DillonB07** [comment]
I have found the mod that causes the issue by removing one at a time and trying to join.
It was this: [https://github.com/SpaceClouds42/PlaytimeTracker](https://github.com/SpaceClouds42/PlaytimeTracker)
Any chance that you or @SpaceClouds42 could try and add some compatibility please?

**Comment by SpaceClouds42** [comment]
I'll take a look later, as samo said the log you provided isn't very helpful, might take a bit to figure it out.

**Comment by DillonB07** [comment]
Sorry about that. I did actually go back and add Gunpowder + Utilities + Pal but it crashed for some reason.

**Comment by samolego** [comment]
I've just come around to fix this, seems like it's PlaytimeTracker's fault.
```
java.lang.NullPointerException: Cannot invoke "us.spaceclouds42.playtime_tracker.duck.AFKPlayer.isAfk()" because "player" is null
```
I'm yet to get more info about it & find where it's caused.

**Comment by SpaceClouds42** [comment]
> Cannot invoke "us.spaceclouds42.playtime_tracker.duck.AFKPlayer.isAfk()" because "player" is null

:concern:
That shouldn't be running on anything but ServerPlayerEntities. I thought Taterzens were their own type of entity..

**Comment by SpaceClouds42** [comment]
Oh, I think it might be [this line](https://github.com/samolego/Taterzens/blob/4c72fe4d07484b09c8cb0ca15d9c0ab5e81881d0/common/src/main/java/org/samo_lego/taterzens/commands/NpcCommand.java#L704)

@DillonB07 were you using the command from console?

**Comment by samolego** [comment]
> > Cannot invoke "us.spaceclouds42.playtime_tracker.duck.AFKPlayer.isAfk()" because "player" is null
> 
> :concern:
> That shouldn't be running on anything but ServerPlayerEntities. I thought Taterzens were their own type of entity..

Yes, they are, that's why it's so strange ...

> Oh, I think it might be this line

This should throw `CommandSyntaxException` if it would be ran from console?

**Comment by SpaceClouds42** [comment]
I thought `getPlayer()` just returns null if the server command source is not a player entity, which would make sense with the error message because the name of the variable is player, as is in the error. Not sure though, might return the syntax exception

**Comment by DillonB07** [comment]
> Oh, I think it might be [this line](https://github.com/samolego/Taterzens/blob/4c72fe4d07484b09c8cb0ca15d9c0ab5e81881d0/common/src/main/java/org/samo_lego/taterzens/commands/NpcCommand.java#L704)
> 
> @DillonB07 were you using the command from console?

No, I wasn't(very late reply sorry!

**Comment by DillonB07** [comment]
Thanks for fixing it though!
