### ISSUE TITLE
FPS drop with The One Probe[Forge ]

### ISSUE THREAD

**Issue by winnetrie83** [samolego/Taterzens#90]
I have reported this issue also with The One Probe:  https://github.com/McJtyMods/TheOneProbe/issues/552#issue-1207388441

Minecraft Version: 1.18.2
Forge Version: 40.0.54
The One Probe Version: theoneprobe-1.18-5.1.0.jar
Taterzen: taterzens-1.8.6-forge.jar

Create a NPC
Look at it and experience FPS drop ( mine went from a steady 60 FPS to 15-20 FPS

The latest.log file was to large for pastebin, so i added the file here. Basicly it is the same error over and over again.
This is a log file while 1 min in game (more or less)
[latest.log](https://github.com/samolego/Taterzens/files/8507811/latest.log)

**Comment by MattB70** [comment]
This still happens on the latest Forge release.

error: https://gist.github.com/MattB70/9175732c4cecf74ec61cb24aef0aa6ab

**Comment by samolego** [comment]
Please report this on theoneprobe issue tracker.
