### ISSUE TITLE
confirmation/error text shows up wrong, right clicking npc's doesn't trigger. am i missing a library? doing it wrong? [Fabric]

### ISSUE THREAD

**Issue by netcore10** [samolego/Taterzens#94]
**Describe the bug**

**Platform(s)**

- [x] Fabric
- [ ] Forge

**Environment(s)**

- [x] Singleplayer
- [x] Server

**Versions**
* Minecraft 1.18.2
* Taterzens 1.9.1

**To Reproduce**
1. Launch server '...'
2. Run '....'
3. Right-click '....'

**Expected behavior**
Errors and confirmations should show with proper text
**Logs**

<details>

</details>

**Additional context**
commands work, text just looks weird.
![image](https://user-images.githubusercontent.com/181536/169910985-d112f43e-4140-4329-875e-62c376b34c2d.png)

**Comment by samolego** [comment]
Can you look if server translations mod is loaded? (Ctrlf through log file)?

**Comment by netcore10** [comment]
i couldn't find any reference to server translations. Here's the log of the current loaded server just incase i missed it
[logs_latest (2).log](https://github.com/samolego/Taterzens/files/8763064/logs_latest.2.log)

i don't think there's an external mod available for 1.18.2 is there?
