### ISSUE TITLE
Right click functionality doesnt work on Blanketcon server [Fabric]

### ISSUE THREAD

**Issue by CammiePone** [samolego/Taterzens#95]
**Describe the bug**
All right click functionality (commands, equipping armour/weapons, etc) doesnt work on the Blanketcon server.

**Platform(s)**

- [x] Fabric
- [ ] Forge

**Environment(s)**

- [x] Singleplayer
- [x] Server

**Versions**
* Minecraft 1.18.2
* Taterzens 1.9.2

**To Reproduce**
1. Create a Taterzen
2. Add a command to it, or go into equipment edit mode
3. Try and right click it to activate the command, or to put the armour/tool on it

**Expected behavior**
I expected the command to fire, or the armour to be equipped on it.

**Logs**

<details>
  <summary>Logs</summary>
It's ridiculously long, and Github wont let me code block it so every line is its own line because of the html formatting.<br>
<a href="https://github.com/samolego/Taterzens/files/8780982/latest.log">latest.log</a>
</details>

**Additional context**
I havent tested in singleplayer, or with just Taterzens, only tested on the Blanketcon server, which has several other mods installed.

EDIT: just tested in singleplayer and the bug persists there. Still no clue about just Taterzens, but if it was just Taterzens, I feel like this bug would've been caught long ago.

**Comment by samolego** [comment]
Fixed, just need to release it now :).

**Comment by CammiePone** [comment]
<3
