### ISSUE TITLE
Incompatible with Minegate - MoreBlocks [Fabric]

### ISSUE THREAD

**Issue by Alkiasan** [samolego/Taterzens#99]
**Describe the bug**
When Taterzens is installed alongside Minegate - Moreblocks, NPCs are unable to be created or loaded.

**Platform(s)**
- [x] Fabric

**Environment(s)**
- [x] Singleplayer
- [x] Server

**Versions**
* Minecraft 1.18.2
* Taterzens 1.9.1

**To Reproduce**
1. Launch server/singleplayer world
2. Create NPC 
3. See error

**Expected behavior**
NPCs are created/loaded normally.

**Logs**
N/A.  Only indication is the error "Duplicate ID value for 15"

**Additional context**
Has been discussed on the Taterzens discord in the past.

**Comment by MrFantiVideo** [comment]
This issue will be fixed in the next version of my mod.
